// Code generated by go-bindata.
// sources:
// scripts/numerics.py
// scripts/system.py
// scripts/web.py
// DO NOT EDIT!

package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _scriptsNumericsPy = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x34\x8c\x41\xaa\x03\x21\x0c\x40\xf7\x39\x45\x98\x95\xc2\x7c\x61\x0e\x30\x77\xf8\x57\xb0\xc5\x19\x52\x62\x0c\x35\x2d\x7a\xfb\xa2\xd3\x6e\x42\x78\x79\x2f\x94\xb5\x3c\x0d\xe5\x95\xb5\x63\xac\x28\x0a\x5f\x94\xa3\x29\x17\x63\xba\x05\xed\x63\x1b\x67\x65\x03\x68\xb8\xa3\x68\x60\x92\xaa\xf1\x9e\xdc\xdf\xb6\xe2\xe6\xa1\x5f\xb8\x92\xb8\xe6\x41\xd9\xc2\xa8\x5c\x5b\xb1\x7b\x00\x23\xe3\x84\x3b\x2e\xff\x5c\x6c\x81\x83\x38\x49\xcc\x93\x0c\x2d\x3c\xf4\x5c\x60\x56\xd3\x74\x73\x5e\x6f\x6a\x7c\xa7\x83\x4e\xf7\x6b\x3c\x7c\x02\x00\x00\xff\xff\x63\xbd\x84\xec\xb6\x00\x00\x00")

func scriptsNumericsPyBytes() ([]byte, error) {
	return bindataRead(
		_scriptsNumericsPy,
		"scripts/numerics.py",
	)
}

func scriptsNumericsPy() (*asset, error) {
	bytes, err := scriptsNumericsPyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scripts/numerics.py", size: 182, mode: os.FileMode(420), modTime: time.Unix(1548698820, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scriptsSystemPy = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func scriptsSystemPyBytes() ([]byte, error) {
	return bindataRead(
		_scriptsSystemPy,
		"scripts/system.py",
	)
}

func scriptsSystemPy() (*asset, error) {
	bytes, err := scriptsSystemPyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scripts/system.py", size: 0, mode: os.FileMode(420), modTime: time.Unix(1548698341, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scriptsWebPy = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func scriptsWebPyBytes() ([]byte, error) {
	return bindataRead(
		_scriptsWebPy,
		"scripts/web.py",
	)
}

func scriptsWebPy() (*asset, error) {
	bytes, err := scriptsWebPyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scripts/web.py", size: 0, mode: os.FileMode(420), modTime: time.Unix(1548698341, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"scripts/numerics.py": scriptsNumericsPy,
	"scripts/system.py": scriptsSystemPy,
	"scripts/web.py": scriptsWebPy,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"scripts": &bintree{nil, map[string]*bintree{
		"numerics.py": &bintree{scriptsNumericsPy, map[string]*bintree{}},
		"system.py": &bintree{scriptsSystemPy, map[string]*bintree{}},
		"web.py": &bintree{scriptsWebPy, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

