#! /usr/bin/env bash
AWS_OPTS='--region=us-west-1 --output text'
CMD=''
while getopts "s:" opt; do
  case ${opt} in
    s ) CMD="$CMD env $OPTARG=`aws $AWS_OPTS --query 'SecretString' secretsmanager get-secret-value --secret-id $OPTARG`"
      ;;
    \? ) echo "Usage: cmd [-s]"
      ;;
  esac
done
shift $((OPTIND -1))
exec $CMD $*
