ALTER TABLE CuratedSnippet ADD Status VARCHAR(255) NOT NULL DEFAULT 'in_progress';
ALTER TABLE CuratedSnippet ADD SnapshotTimestamp BIGINT(20) UNSIGNED NOT NULL;
ALTER TABLE CuratedSnippet ADD SnippetID BIGINT(20) UNSIGNED NOT NULL;
ALTER TABLE CuratedSnippet ADD User VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE CuratedSnippet CHANGE ID SnapshotID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;