ALTER TABLE CuratedSnippet DROP COLUMN Status;
ALTER TABLE CuratedSnippet DROP COLUMN SnapshotTimestamp;
ALTER TABLE CuratedSnippet DROP COLUMN SnippetID;
ALTER TABLE CuratedSnippet DROP COLUMN User;
ALTER TABLE CuratedSnippet CHANGE SnapshotID ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;