---
config:
    instances: 10
    instance_type: "m3.xlarge"

pipeline:
    dedupe:
        input: "s3://kite-emr/users/juan/github-unzip-filter/2016-06-24_18-13-09-PM/python-merge/output/*"
        mapreduce_map_memory_mb: 2000
        mapreduce_reduce_memory_mb: 4000  # this is an upper bound on our output block size